name: myworkflow
on: workflow_dispatch
jobs:
  first-action:
    runs-on: ubuntu-latest
    steps:
    - name: print welcome
      run: echo "Hello, world"

    - name: print Goodbye
      run: |
        echo "byebye",
        echo "section1"

